production:
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] || 'postgres' %>
  database: <%= ENV["POSTGRES_DATABASE"] || ENV["POSTGRES_ENV_POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USER"] || ENV["POSTGRES_ENV_POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || ENV["POSTGRES_ENV_POSTGRES_PASSWORD"] %>
